# Based on: https://nix.dev/tutorials
#                  /nixos/continuous-integration-github-actions.html
#                  #caching-builds-using-github-actions-cache
name: 'Run Tests'
on:
  pull_request:
  push:
jobs:
  run-tests:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'cachix/install-nix-action@v25'
        with:
          nix_path: 'nixpkgs=channel:nixos-unstable'
      - uses: 'DeterminateSystems/magic-nix-cache-action@v2'
      - run: nix-build
      - run: nix-shell --run "pytest"
